<?xml version="1.0"?>
<robot name="imrt_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- INCLUDE -->
  <xacro:include filename="$(find imrt_description)/urdf/range_sensor.urdf.xacro" />

  <!-- RANGE SENSORS -->
  <xacro:add_range_sensor sensor_name="rangesens_1" sensor_xyz="0.16 -0.11 0.091" sensor_rpy="0.0 0.0 0.0" />
  <xacro:add_range_sensor sensor_name="rangesens_2" sensor_xyz="0.16 0.11 0.091" sensor_rpy="0.0 0.0 0.0" />
  <xacro:add_range_sensor sensor_name="rangesens_3" sensor_xyz="0.11 0.16 0.091" sensor_rpy="0.0 0.0 ${pi/2}" />
  <xacro:add_range_sensor sensor_name="rangesens_4" sensor_xyz="-0.11 0.16 0.091" sensor_rpy="0.0 0.0 ${pi/2}" />

  <xacro:arg name="robot_namespace" default="" />
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>$(arg robot_namespace)</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Define constants -->
  <xacro:property name="wheel_radius" value="0.075"/> <!-- meters -->
  <xacro:property name="wheel_length" value="0.027"/> <!-- meters -->
  <xacro:property name="track_width" value="0.336"/> <!-- meters -->

  <!-- Define the base link -->
  <link name="base_link">
    <visual>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://imrt_description/meshes/imrt_base_mesh.dae"/>
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 ${0.225/2}" rpy="0 0 0"/>
        <geometry>
            <cylinder length="0.225" radius="0.1975"/>
        </geometry>
    </collision>
  </link>

  <gazebo reference="base_link">
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
   </gazebo>

  <!-- Define the left wheel -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0007335" ixy="0" ixz="0" iyy="0.0007335" iyz="0" izz="0.00140625"/>
    </inertial>
  </link>

  <gazebo reference="left_wheel_link">
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
        <material>Gazebo/Black</material>
   </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <origin xyz="0 ${track_width/2} ${wheel_radius}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <transmission name="left_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="left_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="left_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
 
  <!-- Define the right wheel -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.0007335" ixy="0" ixz="0" iyy="0.0007335" iyz="0" izz="0.00140625"/>
    </inertial>
  </link>

  <gazebo reference="right_wheel_link">
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
        <material>Gazebo/Black</material>
   </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 ${-track_width/2} ${wheel_radius}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <transmission name="right_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="right_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="right_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>

   <link name="inertial_link">
    <inertial>
        <mass value="4"/>
        <inertia ixx="0.04088125000000001" ixy="0" ixz="0" iyy="0.04088125000000001" iyz="0" izz="0.07801250000000001"/>
    </inertial>
  </link>
  <joint name="inertial_link_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="inertial_link"/>
    <axis xyz="0 1 0"/>
  </joint>
</robot>